--SQL Exercise 5
--1-11 Tennis query

SELECT YEAR_JOINED, Count(*) as Players
FROM PLAYERS
GROUP BY YEAR_JOINED
ORDER BY YEAR_JOINED;

SELECT PLAYERNO, count(*) as Number_Penalities , AVG(AMOUNT) as AvarageAmount
FROM PENALTIES
group by PLAYERNO;



SELECT COUNT(*) as Number_Penalities
FROM PENALTIES
WHERE PEN_DATE < TO_DATE('01-Jan-1983')
order by PEN_DATE;



SELECT Town, COUNT(*) as Number_Players
FROM PLAYERS
GROUP BY Town
HAVING COUNT(*) > 4;



SELECT PLAYERNO
FROM PENALTIES
GROUP BY PLAYERNO
HAVING sum(AMOUNT) > 150;



SELECT PLAYERS.NAME, PLAYERS.INITIALS, COUNT(*) as Penalties
FROM PLAYERS JOIN PENALTIES ON PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
GROUP BY PLAYERS.NAME, PLAYERS.INITIALS
HAVING COUNT(*) > 1;



SELECT EXTRACT(YEAR FROM PEN_DATE) AS PenaltyYear,
       COUNT(*) AS NumPenalties
FROM Penalties
GROUP BY EXTRACT(YEAR FROM PEN_DATE)
HAVING COUNT(*) = 2;



SELECT PLAYERS.NAME, PLAYERS.INITIALS
FROM PLAYERS JOIN (
    SELECT PLAYERNO
    FROM PENALTIES
    WHERE AMOUNT > 40
    GROUP BY PLAYERNO
    HAVING COUNT(*) >= 2
) PENALTIES ON PLAYERS.PLAYERNO = PENALTIES.PLAYERNO;



SELECT DISTINCT PLAYERS.Name, PLAYERS.Initials
FROM PLAYERS Join PENALTIES ON PLAYERS.PLAYERNO = PENALTIES.PLAYERNO
WHERE PENALTIES.AMOUNT = (
    SELECT  MAX(AMOUNT)
    FROM PENALTIES
    ) ;



SELECT Penalty_Year, Num_Penalties
FROM (
    SELECT EXTRACT(YEAR FROM PEN_DATE) AS Penalty_Year,
           COUNT(*) AS Num_Penalties
    FROM Penalties
    GROUP BY EXTRACT(YEAR FROM PEN_DATE)
    ORDER BY Num_Penalties DESC
)
WHERE ROWNUM = 1;



SELECT Playerno, Teamno, (Won - Lost) AS Win_Loss_Difference
FROM MATCHES
ORDER BY Win_Loss_Difference;


















