-- SELECTS AND JOINS;


-- 1;
SELECT JOB_ID, SUM(SALARY) AS Total_Salaray
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY Total_Salaray DESC;



-- 2;
SELECT ROUND(AVG(SALARY),2) AS Avarage_Salary
FROM EMPLOYEES
JOIN JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
WHERE JOB_TITLE != 'President';



-- 3;
SELECT e.FIRST_NAME, e.LAST_NAME, d.DEPARTMENT_NAME
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;



-- 4;
SELECT d.DEPARTMENT_NAME, l.POSTAL_CODE, l.CITY, l.STATE_PROVINCE, l.STREET_ADDRESS
FROM DEPARTMENTS d
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID;



-- 5;
SELECT d.DEPARTMENT_NAME, l.POSTAL_CODE, l.CITY, l.STATE_PROVINCE, l.STREET_ADDRESS, c.COUNTRY_NAME
FROM DEPARTMENTS d
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
JOIN COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID;



-- 6;
SELECT d.DEPARTMENT_NAME, l.POSTAL_CODE, l.CITY, l.STATE_PROVINCE, l.STREET_ADDRESS,
       c.COUNTRY_NAME,
       (FIRST_NAME || ' ' || LAST_NAME) AS MANAGER
FROM DEPARTMENTS d
JOIN LOCATIONS l ON d.LOCATION_ID = l.LOCATION_ID
JOIN COUNTRIES c ON l.COUNTRY_ID = c.COUNTRY_ID
JOIN EMPLOYEES e ON d.MANAGER_ID = e.EMPLOYEE_ID;



-- 7;
SELECT (e.FIRST_NAME || ' ' || e.LAST_NAME) AS NAME, j.JOB_TITLE AS JOB, e.SALARY, d.DEPARTMENT_NAME
FROM EMPLOYEES e
JOIN JOBS j ON j.JOB_ID = e.JOB_ID
JOIN DEPARTMENTS d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;



-- 8;
SELECT LPAD('>',(LEVEL -1) *5, '-') || FIRST_NAME || ' ' || LAST_NAME AS Hierarchy_List
FROM EMPLOYEES
START WITH JOB_ID = (
    SELECT JOB_ID
    FROM JOBS
    WHERE JOB_TITLE = 'President'
    )
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID;








